# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: market.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'market.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmarket.proto\x12\x06market\"\x1e\n\x0cPriceRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\">\n\nPriceReply\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\t2D\n\nMarketData\x12\x36\n\x08GetPrice\x12\x14.market.PriceRequest\x1a\x12.market.PriceReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICEREQUEST']._serialized_start=24
  _globals['_PRICEREQUEST']._serialized_end=54
  _globals['_PRICEREPLY']._serialized_start=56
  _globals['_PRICEREPLY']._serialized_end=118
  _globals['_MARKETDATA']._serialized_start=120
  _globals['_MARKETDATA']._serialized_end=188
# @@protoc_insertion_point(module_scope)
