import grpc
from concurrent import futures
import random
import time
from datetime import datetime

# Template files generated by the protocol buffer compiler and the gRPC Python protocol compiler plugin
import market_pb2
import market_pb2_grpc

# Inherit template class and define methods
class MarketDataServicer(market_pb2_grpc.MarketDataServicer):
    def __init__(self):
        # Initial prices
        self.prices = {
            "BTC": 95000.0,
        }

    def GetPrice(self, request: market_pb2.PriceRequest, context: grpc.ServicerContext) -> market_pb2.PriceReply:
        symbol = request.symbol
        
        if symbol not in self.prices:
            # Error 404 if the request is valid, but the requested resource cannot be given
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details(f"Symbol {symbol} not found")
            return market_pb2.PriceReply()

        # Simulate market movement: +/- 2%
        change = random.uniform(-0.02, 0.02)
        self.prices[symbol] *= (1 + change)
        
        current_price = self.prices[symbol]
        timestamp = datetime.now().strftime("%H:%M:%S")

        print(f"[{timestamp}] {symbol} request received. Current Price: ${current_price:.2f}")

        return market_pb2.PriceReply(
            symbol=symbol,
            price=current_price,
            timestamp=timestamp
        )

def serve():
    # Simultaneous requests set to 10 as this is designed for 1 user
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))

    # Start the server
    market_pb2_grpc.add_MarketDataServicer_to_server(MarketDataServicer(), server)
    server.add_insecure_port('[::]:50051')
    print("Market Engine (gRPC) started on port 50051...")
    server.start()
    server.wait_for_termination()

if __name__ == '__main__':
    serve()
